# Generated by Django 4.0.4 on 2022-04-24 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_settling_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='users_involved',
            field=models.ManyToManyField(related_name='all_debt_expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
