# Generated by Django 4.0.4 on 2022-04-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_management_app', '0002_expense_is_settling_expense_alter_expense_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='is_settling_expense',
            new_name='settled_expense',
        ),
    ]
